[package]
name = "hashglobe"
version = "0.1.0"
authors = ["The Rust Project Developers", "Manish Goregaokar <manishsmail@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Fork of std::HashMap with stable fallible allocation."
documentation = "https://docs.rs/hashglobe"
repository = "https://github.com/Manishearth/hashglobe"
readme = "README.md"
edition = "2018"

[dependencies]
libc = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
