[package]
name = "libmlservo"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
edition = "2018"
publish = false

[lib]
name = "mlservo"
crate-type = ["staticlib"]
test = false
bench = false

[features]
egl = ["simpleservo/egl"]
layout-2013 = ["simpleservo/layout-2013"]
layout-2020 = ["simpleservo/layout-2020"]

[dependencies]
libc = { workspace = true }
libservo = { path = "../../components/servo", features = ["no_static_freetype"] }
log = { workspace = true }
servo-egl = "0.2"
simpleservo = { path = "../libsimpleservo/api", features = ["no_static_freetype"] }
smallvec = { workspace = true }
webxr = { git = "https://github.com/servo/webxr", features = ["ipc", "magicleap"] }
webxr-api = { git = "https://github.com/servo/webxr", features = ["ipc"] }
