version: 1
policy:
  # https://docs.taskcluster.net/docs/reference/integrations/taskcluster-github/docs/taskcluster-yml-v1#pull-requests
  pullRequests: collaborators
tasks:
  - $if: 'tasks_for == "github-push"'
    then:
      taskGroupId: {$eval: as_slugid("decision_task")}
      taskId: {$eval: as_slugid("decision_task")}
      provisionerId: aws-provisioner-v1
      workerType: github-worker
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 hour'}
      metadata:
        name: "Taskcluster experiments for Servo: Decision task"
        description: ""
        owner: ${event.pusher.name}@users.noreply.github.com
        source: ${event.compare}
      scopes:
        - "queue:create-task:aws-provisioner-v1/github-worker"

      payload:
        maxRunTime: 600
        image: "python:2.7.15-stretch"
        features:
          taskclusterProxy: true
        env:
          DECISION_TASK_ID: {$eval: as_slugid("decision_task")}
          GITHUB_EVENT: {$json: {$eval: event}}
        command:
          - /bin/bash
          - '--login'
          - '-c'
          - >-
            git clone ${event.repository.clone_url} repo &&
            cd repo &&
            git checkout ${event.after} &&
            python2.7 -m pip install taskcluster &&
            python2.7 decision-task.py
