version: 1
policy:
  # https://docs.taskcluster.net/docs/reference/integrations/taskcluster-github/docs/taskcluster-yml-v1#pull-requests
  pullRequests: collaborators
tasks:
  - $if: 'tasks_for == "github-push"'
    then:
      taskGroupId: {$eval: as_slugid("decision_task")}
      taskId: {$eval: as_slugid("decision_task")}
      provisionerId: aws-provisioner-v1
      workerType: github-worker
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 hour'}
      metadata:
        name: "Taskcluster experiments for Servo: Decision task"
        description: ""
        owner: ${event.pusher.name}@users.noreply.github.com
        source: ${event.compare}

      payload:
        maxRunTime: 600
        image: "buildpack-deps:bionic-scm"
        features:
          taskclusterProxy: true
        env:
          DECISION_TASK_ID: {$eval: as_slugid("decision_task")}
          DECISION_TASK_OWNER: ${event.pusher.name}@users.noreply.github.com
          DECISION_TASK_SOURCE: ${event.compare}
          DECISION_TASK_CLONE_URL: ${event.repository.clone_url}
          DECISION_TASK_COMMIT_SHA: ${event.after}
        command:
          - /bin/bash
          - '--login'
          - '-c'
          - >-
            git clone $DECISION_TASK_CLONE_URL repo &&
            cd repo &&
            git checkout $DECISION_TASK_COMMIT_SHA &&
            pip install taskcluster &&
            python2.7 decision-task.py
