version: 1
policy:
  # https://docs.taskcluster.net/docs/reference/integrations/taskcluster-github/docs/taskcluster-yml-v1#pull-requests
  pullRequests: collaborators
tasks:
  - $if: 'tasks_for == "github-push"'
    then:
      taskGroupId: {$eval: as_slugid("decision_task")}
      taskId: {$eval: as_slugid("decision_task")}
      provisionerId: aws-provisioner-v1
      workerType: servo-docker-worker
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 hour'}
      metadata:
        name: "Taskcluster experiments for Servo: decision task"
        description: ""
        owner: ${event.pusher.name}@users.noreply.github.com
        source: ${event.compare}
      scopes:
        - "queue:create-task:aws-provisioner-v1/github-worker"
        - "docker-worker:cache:cargo-registry-cache"
        - "docker-worker:cache:cargo-git-cache"

      payload:
        maxRunTime: 1200
        image: "buildpack-deps:bionic-scm"
        features:
          taskclusterProxy: true
        env:
          GITHUB_EVENT_OWNER: ${event.pusher.name}@users.noreply.github.com
          GITHUB_EVENT_SOURCE: ${event.compare}
          GITHUB_EVENT_CLONE_URL: ${event.repository.clone_url}
          GITHUB_EVENT_COMMIT_SHA: ${event.after}
        command:
          - /bin/bash
          - '--login'
          - '-c'
          - >-
            git clone $GITHUB_EVENT_CLONE_URL repo &&
            cd repo &&
            git checkout $GITHUB_EVENT_COMMIT_SHA &&
            python2.7 decision-task/run.py
