version: 1
policy:
  # https://docs.taskcluster.net/docs/reference/integrations/taskcluster-github/docs/taskcluster-yml-v1#pull-requests
  pullRequests: collaborators
tasks:
  - $if: 'tasks_for == "github-push"'
    then:
      provisionerId: aws-provisioner-v1
      workerType: github-worker
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 hour'}
      metadata:
        name: "Taskcluster experiments for Servo"
        description: "Initial task"
        owner: ${event.pusher.name}@users.noreply.github.com
        source: ${event.compare}

      payload:
        maxRunTime: 600
        image: "buildpack-deps:bionic-scm"
        features:
          taskclusterProxy: true
        command:
          - /bin/bash
          - '--login'
          - '-c'
          - >-
            git clone ${event.repository.clone_url} repo &&
            cd repo &&
            git checkout ${event.after} &&
            python2.7 task.py
