[package]
name = "layout_2020"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
edition = "2018"
publish = false

[lib]
name = "layout"
path = "lib.rs"
test = false
doctest = false

[dependencies]
app_units = "0.7"
atomic_refcell = "0.1"
euclid = "0.20"
gfx = {path = "../gfx"}
ipc-channel = "0.12"
libc = "0.2"
msg = {path = "../msg"}
rayon = "1"
rayon_croissant = "0.1.1"
script_layout_interface = {path = "../script_layout_interface"}
script_traits = {path = "../script_traits"}
serde = "1.0"
servo_arc = { path = "../servo_arc" }
style = {path = "../style", features = ["servo", "servo-layout-2020"]}
style_traits = {path = "../style_traits"}
webrender_api = {git = "https://github.com/servo/webrender", features = ["ipc"]}
