name: Release nightly

on:
  schedule:
    # Run at 5:30 am, daily.
    - cron: '15 5 * * *'
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash

jobs:
  upload-win:
    # This job is only useful when run on upstream servo.
    if: github.repository == 'servo/servo' || github.event_name == 'workflow_dispatch'
    name: Upload nightly (Windows)
    uses: ./.github/workflows/windows.yml
    with:
      layout: '2013'
      upload: true

  upload-mac:
    # This job is only useful when run on upstream servo.
    if: github.repository == 'servo/servo' || github.event_name == 'workflow_dispatch'
    name: Upload nightly (macOS)
    uses: ./.github/workflows/mac.yml
    with:
      layout: '2013'
      upload: true

  upload-linux:
    # This job is only useful when run on upstream servo.
    if: github.repository == 'servo/servo' || github.event_name == 'workflow_dispatch'
    name: Upload nightly (Linux)
    uses: ./.github/workflows/linux.yml
    with:
      layout: '2013'
      upload: true

  upload-linux-2020:
    # This job is only useful when run on upstream servo.
    if: github.repository == 'servo/servo' || github.event_name == 'workflow_dispatch'
    name: Upload nightly (Linux layout2020)
    uses: ./.github/workflows/linux.yml
    with:
      layout: '2020'
      upload: true
