name: Pull request
on:
  pull_request:
    types: ['opened', 'synchronize']
    branches: ["**"]


jobs:
  build-linux:
    name: Linux
    if: github.repository == 'servo/servo'
    uses: ./.github/workflows/linux.yml
    with:
      layout: '2013'
      unit-tests: true

  build-linux-layout-2020:
    name: Linux (layout-2020)
    if: github.repository == 'servo/servo'
    uses: ./.github/workflows/linux.yml
    with:
      layout: '2020'
      unit-tests: false