name: WPT exporter test
on:
  pull_request:
    branches: ["**"]
    paths: ["python/wpt/exporter/**"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade -r python/wpt/requirements-dev.txt
      - name: Running tests
        run: |
          python3 python/wpt/test.py
